name: Testes pós commit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Validação de repositório
      uses: actions/checkout@v2

    - name: Configurando Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Instalando dependências
      run: |
        npm install
        npm ci

    - name: Executando testes
      run: |
        npx playwright test

    - name: Gerando Relatorio
      uses: allure-framework/allure-report-action@v2
      with:
        allure_results: ./allure-results
        allure_report:  ./allure-report