name: Testes pós commit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Validação de repositório
      uses: actions/checkout@v2

    - name: Configurando Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Instalando dependências
      run: |
        npm install
        npm ci

    - name: Executando testes
      run: |
        npx playwright test

    - name: Gerando Relatorio
      uses: simple-elf/allure-report-action@v1.6
      with:
        allure_results: ./allure-results
        allure_report:  ./allure-report

    - name: Upload do relatório Allure
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report
    